name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Prettier format
        run: npm run prettier

      - name: ESLint check
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Generate docs
        run: npm run docs

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload page artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'docs'
          path: docs/

  release-please:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: test
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - name: Checkout code
        if: steps.release.outputs.release_created == 'true'
        uses: actions/checkout@v3

      - name: Setup Node.js
        if: steps.release.outputs.release_created == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.release.outputs.release_created == 'true'
        run: npm ci

      - name: Download build artifacts
        if: steps.release.outputs.release_created == 'true'
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to npm
        if: steps.release.outputs.release_created == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

      - name: Download docs artifacts
        if: steps.release.outputs.release_created == 'true'
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs/

      - name: Commit and push docs
        if: steps.release.outputs.release_created == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update documentation"
            git push -o ci.skip
          fi
